# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistrationlink',
            name='link',
        ),
        migrations.AddField(
            model_name='userregistrationlink',
            name='slug',
            field=models.CharField(default='', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
