# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_tracker', '0003_auto_20160402_1338'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchaseorderstatus',
            table='purchase_order_status',
        ),
    ]
