# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 11:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery_tracker', '0004_auto_20160402_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_link', models.CharField(blank=True, max_length=1024, null=True)),
                ('product_link', models.CharField(max_length=1024)),
                ('vendor_code', models.CharField(blank=True, max_length=64, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(max_length=32)),
                ('size', models.CharField(max_length=32)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('discount_code', models.CharField(blank=True, max_length=64, null=True)),
                ('discount_in_shop', models.CharField(blank=True, max_length=64, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery_tracker.PurchaseOrder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
